[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "baal"
version = "0.1.0"
description = "Orchestration repository for data pipelines"
requires-python = ">=3.12"
dependencies = [
    "prefect",
    "pandas",
    "requests",
    "boto3",  # For AWS S3 operations
    "tanit @ git+https://github.com/iSkaCh/tanit.git", 
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["orchestration*"]

[tool.black]
line-length = 88
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
